IF (OBJECT_ID('NullableTestClass') IS NOT NULL)
BEGIN
    DROP TABLE NullableTestClass
END

CREATE TABLE NullableTestClass (
	Id INT IDENTITY(1,1) NOT NULL,
	StringVal NVARCHAR(100) NOT NULL,
	StringVal2 NVARCHAR(100) NULL,
	IntVal INT NOT NULL,
	NullableIntVal INT NULL DEFAULT(0),
	DTVal NVARCHAR(100) NULL,
	NullableDTVal NVARCHAR(100) NULL DEFAULT(GETUTCDATE()),
	EnumVal NVARCHAR(20) NOT NULL,
	NullableEnumVal NVARCHAR(20) NULL,
	BlobField VARBINARY(MAX) NULL
)
